### ISSUE TITLE
build from sources

### ISSUE THREAD

**Issue by kostyrev** [lobsterdore/ansible-fabio#4]
Hello!
For my environment I see no reason to build go and then build fabio.
If I send you PR with the way to download compiled fabio, would you consider it?

**Comment by lobsterdore** [comment]
Sure thing, I don't see any reason why not.

**Comment by magiconair** [comment]
fabio author here: That would also address #6.

**Comment by magiconair** [comment]
You might want to remove the code for building fabio from source altogether since - if I read this correctly - the default is still to install fabio from source with an outdated and incompatible Go version.

**Comment by kostyrev** [comment]
@magiconair or just set go 1.7 as default as in 57304cb

**Comment by magiconair** [comment]
@kostyrevaa This makes only sense if this gets updated properly. Since the go version was not only several releases behind (1.5 vs 1.7) but also not current within the 1.5 cycle (1.5.1 vs 1.5.4) the chance for this build missing a security patch is high. I'm keeping the fabio packages up-to-date and *all* fabio users are benefiting from this.

**Comment by kostyrev** [comment]
@magiconair agreed. thanks for clarification.
On the other hand, what if I want to build from master and not the release, because I'm a weirdo.
I think setting [this](https://github.com/lobsterdore/ansible-fabio/blob/master/defaults/main.yml#L14) to `false` by default will suit both cases.
